### ISSUE TITLE
Kafka integration tests in Juju 3.1.8 due to vm swappiness setting of 60 (which is highter than 1)

### ISSUE THREAD

**Issue by shayancanonical** [canonical/data-integrator#52]
## Steps to reproduce
Run nightly tests in data integrator
Example run: https://github.com/canonical/data-integrator/actions/runs/9590090519/job/26444999201

## Expected behavior
Kafka tests pass in both Juju 2.4.49 and Juju 3.1.8

## Actual behavior
Tests do not pass due to below error resulting in `TimeoutError`s

## Versions
Operating system: Ubuntu 22.04.4
Juju agent:  juju 3.1.8
Charm revision: 61

## Log output
```
...
unit-kafka-0: 02:03:42 ERROR unit.kafka/0.juju-log machine vm.swappiness setting of 60 is higher than 1 - set /etc/syscl.conf vm.swappiness=1 and restart machine
...
```

**Comment by taurus-forever** [comment]
@shayancanonical as I can see this is no longer relevant: https://github.com/canonical/data-integrator/actions/runs/10712114421
Please reopen if I am wrong here. Tnx!
